import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { RefreshCw, CheckCircle, AlertCircle, GripVertical, X } from 'lucide-react';
import { cn } from '@/lib/utils';

interface AIColumnMapperProps {
  importLogId: string;
  onProcessComplete: () => void;
  initialPrompt: string;
}

// Schema delle colonne target di imported_contacts
const TARGET_SCHEMA = [
  { key: 'name', label: 'Nome', description: 'Nome del contatto' },
  { key: 'alias', label: 'Alias', description: 'Alias/Soprannome' },
  { key: 'position', label: 'Posizione', description: 'Ruolo/Posizione' },
  { key: 'title', label: 'Titolo', description: 'Titolo (es. Dott., Ing.)' },
  { key: 'phone', label: 'Telefono', description: 'Numero telefono' },
  { key: 'cell', label: 'Cellulare', description: 'Numero cellulare' },
  { key: 'email', label: 'Email', description: 'Indirizzo email' },
  { key: 'company_name', label: 'Azienda', description: 'Nome azienda' },
  { key: 'company_alias', label: 'Alias Azienda', description: 'Alias azienda' },
  { key: 'address', label: 'Indirizzo', description: 'Via e numero civico' },
  { key: 'city', label: 'Città', description: 'Città' },
  { key: 'zip_code', label: 'CAP', description: 'Codice postale' },
  { key: 'country', label: 'Paese', description: 'Nazione' },
  { key: 'note', label: 'Note', description: 'Note aggiuntive' },
  { key: 'origin', label: 'Origine', description: 'Provenienza contatto' },
  { key: 'client_code', label: 'Codice Cliente', description: 'Codice identificativo' },
];

interface ColumnMapping {
  targetColumn: string;
  sourceColumn: string | null;
  confidence: 'high' | 'medium' | 'low' | 'none';
}

export function AIColumnMapper({ importLogId, onProcessComplete, initialPrompt }: AIColumnMapperProps) {
  const [tempData, setTempData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [processing, setProcessing] = useState(false);
  const [additionalInstructions, setAdditionalInstructions] = useState('');
  const [mappings, setMappings] = useState<ColumnMapping[]>([]);
  const [sourceColumns, setSourceColumns] = useState<string[]>([]);
  const [draggedColumn, setDraggedColumn] = useState<string | null>(null);
  const [autoGeneratedPrompt, setAutoGeneratedPrompt] = useState('');

  useEffect(() => {
    loadTempData();
  }, [importLogId]);

  const loadTempData = async () => {
    try {
      setLoading(true);
      
      const { data, error } = await supabase
        .from('temp_ai_import')
        .select('*')
        .eq('import_log_id', importLogId)
        .order('row_number', { ascending: true });

      if (error) throw error;

      setTempData(data || []);
      
      if (data && data.length > 0) {
        const rawFields = Object.keys(data[0].raw_data || {});
        setSourceColumns(rawFields);
        initializeMappings(rawFields);
      }
    } catch (error: any) {
      toast.error(`Errore caricamento dati: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const initializeMappings = (sourceFields: string[]) => {
    const initialMappings: ColumnMapping[] = TARGET_SCHEMA.map(target => {
      const match = findBestMatch(target.key, sourceFields);
      return {
        targetColumn: target.key,
        sourceColumn: match.column,
        confidence: match.confidence
      };
    });
    
    setMappings(initialMappings);
    generatePromptFromMappings(initialMappings);
  };

  const findBestMatch = (targetKey: string, sourceFields: string[]): { column: string | null; confidence: 'high' | 'medium' | 'low' | 'none' } => {
    const normalizedTarget = targetKey.toLowerCase().replace(/_/g, '');
    
    for (const source of sourceFields) {
      const normalizedSource = source.toLowerCase().replace(/[_\s]/g, '');
      
      if (normalizedSource === normalizedTarget) {
        return { column: source, confidence: 'high' };
      }
      
      if (normalizedSource.includes(normalizedTarget) || normalizedTarget.includes(normalizedSource)) {
        return { column: source, confidence: 'medium' };
      }
    }
    
    return { column: null, confidence: 'none' };
  };

  const handleDragStart = (e: React.DragEvent, columnName: string) => {
    setDraggedColumn(columnName);
    e.dataTransfer.effectAllowed = 'move';
  };

  const handleDragEnd = () => {
    setDraggedColumn(null);
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
  };

  const handleDrop = (e: React.DragEvent, targetColumn: string) => {
    e.preventDefault();
    
    if (!draggedColumn) return;

    const newMappings = mappings.map(m => {
      if (m.targetColumn === targetColumn) {
        return { ...m, sourceColumn: draggedColumn, confidence: 'high' as const };
      }
      if (m.sourceColumn === draggedColumn) {
        return { ...m, sourceColumn: null, confidence: 'none' as const };
      }
      return m;
    });

    setMappings(newMappings);
    generatePromptFromMappings(newMappings);
    setDraggedColumn(null);
  };

  const handleRemoveMapping = (targetColumn: string) => {
    const newMappings = mappings.map(m => 
      m.targetColumn === targetColumn 
        ? { ...m, sourceColumn: null, confidence: 'none' as const }
        : m
    );
    setMappings(newMappings);
    generatePromptFromMappings(newMappings);
  };

  const generatePromptFromMappings = (currentMappings: ColumnMapping[]) => {
    const mappingInstructions = currentMappings
      .filter(m => m.sourceColumn)
      .map(m => {
        const targetInfo = TARGET_SCHEMA.find(t => t.key === m.targetColumn);
        return `- Mappa il campo "${m.sourceColumn}" a "${m.targetColumn}" (${targetInfo?.label})`;
      })
      .join('\n');

    const unmappedTarget = currentMappings
      .filter(m => !m.sourceColumn)
      .map(m => {
        const targetInfo = TARGET_SCHEMA.find(t => t.key === m.targetColumn);
        return targetInfo?.key;
      });

    const prompt = `Istruzioni di mappatura:\n\n${mappingInstructions}\n\n${
      unmappedTarget.length > 0 
        ? `Campi non mappati (lascia vuoti): ${unmappedTarget.join(', ')}`
        : ''
    }`;

    setAutoGeneratedPrompt(prompt);
  };

  const handleProcessWithMapping = async () => {
    setProcessing(true);
    try {
      const fullPrompt = `${initialPrompt}\n\n${autoGeneratedPrompt}${
        additionalInstructions ? `\n\nIstruzioni aggiuntive:\n${additionalInstructions}` : ''
      }`;

      const { data, error } = await supabase.functions.invoke('process-ai-import', {
        body: {
          importLogId,
          aiPrompt: fullPrompt
        }
      });

      if (error) throw error;

      if (data.success) {
        toast.success(`Elaborazione completata: ${data.data.processedRecords} contatti processati`);
        onProcessComplete();
      }
    } catch (error: any) {
      toast.error(`Errore elaborazione: ${error.message}`);
    } finally {
      setProcessing(false);
    }
  };

  const getUnmappedSourceColumns = () => {
    const mappedSources = new Set(mappings.filter(m => m.sourceColumn).map(m => m.sourceColumn));
    return sourceColumns.filter(col => !mappedSources.has(col));
  };

  if (loading) {
    return (
      <Card>
        <CardContent className="p-8 text-center">
          <RefreshCw className="h-8 w-8 animate-spin text-muted-foreground mx-auto" />
          <p className="text-sm text-muted-foreground mt-2">Caricamento dati...</p>
        </CardContent>
      </Card>
    );
  }

  const unmappedCount = mappings.filter(m => !m.sourceColumn).length;
  const mappedCount = mappings.filter(m => m.sourceColumn).length;

  return (
    <div className="space-y-6">
      {/* Mapping Stats */}
      <Card>
        <CardHeader>
          <CardTitle>Mappatura Colonne - Drag & Drop</CardTitle>
          <CardDescription>
            Trascina le colonne del file (sotto) sulle colonne target (sopra) per creare il mapping
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4 text-sm">
            <Badge variant="default" className="bg-green-600">
              <CheckCircle className="h-3 w-3 mr-1" />
              Mappati: {mappedCount}
            </Badge>
            <Badge variant="destructive" className="bg-red-600">
              <AlertCircle className="h-3 w-3 mr-1" />
              Non mappati: {unmappedCount}
            </Badge>
          </div>
        </CardContent>
      </Card>

      {/* Mapping Grid */}
      <div className="grid gap-3">
        {TARGET_SCHEMA.map((target) => {
          const mapping = mappings.find(m => m.targetColumn === target.key);
          const isMapped = !!mapping?.sourceColumn;
          
          return (
            <Card key={target.key} className={cn(
              "transition-colors",
              !isMapped && "border-red-300 bg-red-50/50"
            )}>
              <CardContent className="p-4">
                <div className="space-y-3">
                  {/* Target Column */}
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-semibold text-sm">{target.label}</div>
                      <div className="text-xs text-muted-foreground">{target.description}</div>
                    </div>
                    <Badge variant={isMapped ? "default" : "destructive"}>
                      {target.key}
                    </Badge>
                  </div>

                  {/* Drop Zone */}
                  <div
                    onDragOver={handleDragOver}
                    onDrop={(e) => handleDrop(e, target.key)}
                    className={cn(
                      "min-h-[60px] border-2 border-dashed rounded-lg p-3 transition-all",
                      isMapped 
                        ? "border-green-500 bg-green-50/50" 
                        : "border-gray-300 bg-gray-50",
                      draggedColumn && "border-primary bg-primary/5"
                    )}
                  >
                    {mapping?.sourceColumn ? (
                      <div className="flex items-center justify-between rounded px-3 py-2 shadow-sm">
                        <div className="flex items-center gap-2">
                          <GripVertical className="h-4 w-4 text-muted-foreground" />
                          <span className="font-mono text-sm">{mapping.sourceColumn}</span>
                        </div>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleRemoveMapping(target.key)}
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                    ) : (
                      <div className="text-center text-sm text-muted-foreground py-4">
                        Trascina qui una colonna del file
                      </div>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Available Source Columns */}
      <Card>
        <CardHeader>
          <CardTitle>Colonne File Importato</CardTitle>
          <CardDescription>
            Trascina queste colonne sulle zone target sopra
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-2">
            {getUnmappedSourceColumns().map((column) => (
              <div
                key={column}
                draggable
                onDragStart={(e) => handleDragStart(e, column)}
                onDragEnd={handleDragEnd}
                className={cn(
                  "px-4 py-2 rounded-lg border-2 cursor-move transition-all",
                  "bg-white hover:bg-gray-50 hover:shadow-md",
                  draggedColumn === column && "opacity-50 scale-95"
                )}
              >
                <div className="flex items-center gap-2">
                  <GripVertical className="h-4 w-4 text-muted-foreground" />
                  <span className="font-mono text-sm">{column}</span>
                </div>
              </div>
            ))}
            {getUnmappedSourceColumns().length === 0 && (
              <p className="text-sm text-muted-foreground">
                Tutte le colonne sono state mappate
              </p>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Generated Prompt Preview */}
      <Card>
        <CardHeader>
          <CardTitle>Prompt Generato Automaticamente</CardTitle>
          <CardDescription>
            Basato sulla mappatura che hai creato
          </CardDescription>
        </CardHeader>
        <CardContent>
          <pre className="text-xs bg-muted p-4 rounded-lg overflow-auto max-h-[200px]">
            {autoGeneratedPrompt}
          </pre>
        </CardContent>
      </Card>

      {/* Additional Instructions */}
      <Card>
        <CardHeader>
          <CardTitle>Istruzioni Aggiuntive (Opzionale)</CardTitle>
          <CardDescription>
            Aggiungi dettagli extra per la trasformazione dei dati
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Textarea
            value={additionalInstructions}
            onChange={(e) => setAdditionalInstructions(e.target.value)}
            placeholder="Es: Converti tutti i numeri di telefono aggiungendo il prefisso +39..."
            rows={4}
            className="resize-none"
          />

          <Button
            onClick={handleProcessWithMapping}
            disabled={processing || unmappedCount === mappings.length}
            className="w-full"
            size="lg"
          >
            {processing ? (
              <>
                <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                Elaborazione in corso...
              </>
            ) : (
              <>
                <CheckCircle className="h-4 w-4 mr-2" />
                Avvia Importazione con Questa Mappatura
              </>
            )}
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
