-- Create storage bucket for chat attachments
INSERT INTO storage.buckets (id, name, public)
VALUES ('chat-attachments', 'chat-attachments', true);

-- RLS policies for chat attachments bucket
CREATE POLICY "Users can upload their own chat attachments"
ON storage.objects
FOR INSERT
WITH CHECK (
  bucket_id = 'chat-attachments' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

CREATE POLICY "Users can view their own chat attachments"
ON storage.objects
FOR SELECT
USING (
  bucket_id = 'chat-attachments' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

CREATE POLICY "Users can delete their own chat attachments"
ON storage.objects
FOR DELETE
USING (
  bucket_id = 'chat-attachments' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

-- Add columns to chat_messages for attachments and images
ALTER TABLE public.chat_messages
ADD COLUMN IF NOT EXISTS attachments jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS images jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS generated_images jsonb DEFAULT '[]'::jsonb;

COMMENT ON COLUMN public.chat_messages.attachments IS 'Array of attachment objects with {name, url, type, size}';
COMMENT ON COLUMN public.chat_messages.images IS 'Array of image URLs sent as input to the model';
COMMENT ON COLUMN public.chat_messages.generated_images IS 'Array of base64 or URL images generated by AI';